a='my name is ankit\n i have completed my   PG(MCA) in 2020'
c=a.count('a')
m=a.capitalize()
g=len(a)
k=a.find('completed')
p=a.replace('have completed','did')
d=a.find('  ')
mn= a.replace('  PG','Post Graduation')
print(c)
print(g)
print(m)
print(k)
print(p)
print(d)
print(mn)