n1=int(input('enter the number'))
n2=int(input('enter the number'))
n3=int(input('enter the number'))
n4=int(input('enter the number'))
n5=input('enter the number')
n6=int(input('enter the number'))
n7=int(input('enter the number'))
n8=int(input('enter the number'))
n9=int(input('enter the number'))
a={n1,n2,n3,n4,n5,n6,n7,n8}
a.add(n9)
print(a)
print(len(a))
