a=int(input('enter number'))
b=int(input('enter number'))
c=int(input('enter number'))
d=int(input('enter number'))
e=int(input('enter number'))
f=int(input('enter number'))
g=int(input('enter number'))
T= (a,b,c,d,e,f,g)
print(T.count(0))
print(T.index(9))